[[redirects]]
  from = "/api/*"
  to = "https://jobmentum.onrender.com/api/v1/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://jomentum.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
